# Generated by Django 5.0.2 on 2024-02-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_facture',
            fields=[
                ('id_cat_facture', models.AutoField(db_column='id_cat_facture', default=None, primary_key=True, serialize=False)),
                ('nom_cat_facture', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Cat_facture',
            },
        ),
        migrations.CreateModel(
            name='Civilite',
            fields=[
                ('id_civi', models.AutoField(db_column='id_civi', default=None, primary_key=True, serialize=False)),
                ('nom_civi', models.CharField(max_length=14)),
                ('abbr_civi', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Civilite',
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id_devise', models.AutoField(db_column='id_devise', default=None, primary_key=True, serialize=False)),
                ('nom_devise', models.CharField(max_length=40)),
                ('abbr_devise', models.CharField(max_length=6)),
                ('symb_devise', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Devise',
            },
        ),
        migrations.CreateModel(
            name='Methode_paiement',
            fields=[
                ('id_m_paie', models.AutoField(db_column='id_m_paie', default=None, primary_key=True, serialize=False)),
                ('nom_m_paie', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Fethode_paiement',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id_pays', models.CharField(db_column='id_pays', default=None, max_length=3, primary_key=True, serialize=False)),
                ('nom_pays', models.CharField(max_length=45)),
                ('indicatif_pays', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(db_column='id_client', default=None, primary_key=True, serialize=False)),
                ('r_social_client', models.CharField(max_length=100, null=True)),
                ('siret_client', models.CharField(db_index=True, max_length=14, null=True)),
                ('nom_client', models.CharField(max_length=40)),
                ('prenom_client', models.CharField(max_length=40)),
                ('adr_client', models.CharField(max_length=100)),
                ('adr2_client', models.CharField(max_length=100, null=True)),
                ('tel_client', models.IntegerField(null=True)),
                ('mail_client', models.CharField(max_length=180, null=True)),
                ('civilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.civilite')),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fourn', models.AutoField(db_column='id_fourn', default=None, primary_key=True, serialize=False)),
                ('r_social_fourn', models.CharField(max_length=100)),
                ('siret_fourn', models.CharField(db_index=True, max_length=14)),
                ('nom_fourn', models.CharField(max_length=40, null=True)),
                ('prenom_fourn', models.CharField(max_length=40, null=True)),
                ('adr_fourn', models.CharField(max_length=100)),
                ('adr2_fourn', models.CharField(max_length=100, null=True)),
                ('tel_fourn', models.IntegerField(null=True)),
                ('mail_fourn', models.CharField(max_length=180, null=True)),
                ('civilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.civilite')),
            ],
            options={
                'db_table': 'Fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_reg', models.AutoField(db_column='id_reg', default=None, primary_key=True, serialize=False)),
                ('nom_reg', models.CharField(max_length=60)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.pays')),
            ],
            options={
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(db_column='id_user', default=None, primary_key=True, serialize=False)),
                ('nom_user', models.CharField(max_length=40)),
                ('prenom_user', models.CharField(max_length=40)),
                ('adr_user', models.CharField(max_length=100)),
                ('adr2_user', models.CharField(max_length=100, null=True)),
                ('tel_user', models.IntegerField(null=True)),
                ('mail_user', models.CharField(max_length=180, unique=True)),
                ('mdp_user', models.CharField(max_length=254)),
                ('sel_user', models.CharField(max_length=254)),
                ('civilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.civilite')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.AutoField(db_column='id_facture', default=None, primary_key=True, serialize=False)),
                ('num_facture', models.CharField(db_index=True, max_length=40)),
                ('date_facture', models.DateField()),
                ('total_ht_facture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ttc_facture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_facture', models.BooleanField(default=True)),
                ('cat_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.cat_facture')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.client')),
                ('devise', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.devise')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.fournisseur')),
                ('methode_paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.methode_paiement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.user')),
            ],
            options={
                'db_table': 'Facture',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id_ville', models.AutoField(db_column='id_ville', default=None, primary_key=True, serialize=False)),
                ('nom_ville', models.CharField(max_length=60)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.region')),
            ],
            options={
                'db_table': 'Ville',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.ville'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.ville'),
        ),
        migrations.CreateModel(
            name='Cp',
            fields=[
                ('cp', models.CharField(db_column='cp', default=None, max_length=9, primary_key=True, serialize=False)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.ville')),
            ],
            options={
                'db_table': 'Cp',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logifacturapp.ville'),
        ),
    ]
