# Generated by Django 5.0.2 on 2024-02-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logifacturapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='methode_paiement',
            table='Methode_paiement',
        ),
    ]
