# Generated by Django 5.0.2 on 2024-02-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logifacturapp', '0003_alter_fournisseur_civilite'),
    ]

    operations = [
    ]
