# Generated by Django 5.0.2 on 2024-02-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logifacturapp', '0005_alter_facture_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
