# Generated by Django 5.0.2 on 2024-02-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logifacturapp', '0007_agendaevent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendaevent',
            table='Agenda_Event',
        ),
    ]
