# Generated by Django 5.0.2 on 2024-03-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logifacturapp', '0008_alter_agendaevent_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='num_facture',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
